[build-system]
requires = ["setuptools==84.0.0", "setuptools_scm==10.3.2"]
build-backend = "setuptools.build_meta"

[project]
name = "objctypes"
description = "Use Objective-C features in Python"
readme = "README.md"
requires-python = ">=3.13"
license = "Unlicense"
license-files = ["LICENSE.md"]
keywords = ["objctypes", "objc", "Objective-C", "ObjectiveC"]
classifiers = [
  "Development Status :: 1 - Planning",
  "Environment :: MacOS X :: Cocoa",
  "Intended Audience :: Developers",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: iOS",
  "Programming Language :: Objective C",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Typing :: Typed",
]
dynamic = ["version"]

[project.urls]
Source = "https://github.com/qqfunc/objctypes"
Documentation = "https://objctypes.readthedocs.io/"
Issues = "https://github.com/qqfunc/objctypes/issues"

[dependency-groups]
check = [
  "editorconfig-checker==3.11.1",
  "ruff==0.15.22",
  "ty==0.0.82",
  "types-setuptools==84.0.0.20260812",
  "typos==1.50.2",
]
tests = ["pytest==9.1.1", "pytest-xdist==3.8.0"]
docs = [
  "furo==2025.12.19",
  "packaging==26.3",
  "sphinx==9.1.0",
  "sphinx-autoapi==3.8.1",
  "sphinx-copybutton==0.5.2",
  "sphinx-lint==1.0.2",
  "sphinx-notfound-page==1.1.0",
]
misc = ["taskipy==1.14.1"]
dev = [
  { include-group = "check" },
  { include-group = "tests" },
  { include-group = "docs" },
  { include-group = "misc" },
  "committed==1.1.11",
  "lefthook==2.1.14",
  "sphinx-autobuild==2025.8.25",
]
gh-actions-build = [
  { include-group = "tests" },
  "pytest-github-actions-annotate-failures==0.4.2",
]
gh-actions-check = [
  { include-group = "check" },
  { include-group = "docs" },
  { include-group = "tests" },
  { include-group = "misc" },
]
readthedocs = [{ include-group = "docs" }]

[tool.pyright]
typeCheckingMode = "off" # Disable type checking in editors

[tool.pytest.ini_options]
addopts = "-n auto"

[tool.ruff]
line-length = 79
format.docstring-code-line-length = 72
lint.select = ["ALL"]
lint.ignore = [
  "COM812", # missing-trailing-comma
  "PYI021", # docstring-in-stub
  "PT011",  # pytest-raises-too-broad
  "D203",   # one-blank-line-before-class
  "D213",   # multi-line-summary-second-line
  "D418",   # overload-with-docstring
]
lint.per-file-ignores."src/**/*.pyi" = [
  "ANN401" # any-type
]
lint.per-file-ignores."setup.py" = [
  "S603", # subprocess-without-shell-equals-true
]
lint.per-file-ignores."docs/conf.py" = [
  "INP001", # implicit-namespace-package
]
lint.per-file-ignores."tests/**.py" = [
  "S101",    # assert
  "INP001",  # implicit-namespace-package
  "PLR2004", # magic-value-comparison
]
lint.pycodestyle.max-doc-length = 72

[tool.setuptools_scm]

[tool.taskipy.settings]
use_vars = true
cwd = "."

[tool.taskipy.variables]
docs = "./docs"
docs-build = { var = "{docs}/_build", recursive = true }

[tool.taskipy.tasks]
setup = { cmd = "lefthook install", help = "set up the project" }
check = { cmd = "lefthook run check", help = "check the code" }
fix = { cmd = "lefthook run fix", help = "check and fix the code" }
test = { cmd = "pytest", help = "Run unit tests with pytest" }
docs-build = { cmd = "sphinx-build {docs} {docs-build}", help = "Build the documentation with Sphinx" }
docs-autobuild = { cmd = "sphinx-autobuild {docs} {docs-build}", help = "Build the documentation with sphinx-autobuild" }
docs-lint = { cmd = "sphinx-lint -i .venv -i {docs-build}", help = "Lint the documentation with sphinx-lint" }

[tool.ty]
terminal.error-on-warning = true

[tool.typos]
files.extend-exclude = ["uv.lock"]
default.unicode = false

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "setup.py" }, { file = "csrc/**/*" }]
